### ISSUE TITLE
TryReserveError is not re-exported

### ISSUE THREAD

**Issue by CeleritasCelery** [zakarumych/allocator-api2#12]
The version of `TryReserveError` from allocator_api2 is not publicly re-exported, so it cannot be named in types. Unless there is a specific reason for this, it seems like it should be exported to make it at least as useful as the std-lib version.

Also the [docs](https://docs.rs/allocator-api2/latest/allocator_api2/vec/struct.Vec.html#method.try_reserve) for `try_reserve` still reference the one in `std::collections`.

**Comment by zakarumych** [comment]
Should've been fixed in a16a359038cf741aa6445809e33a845e17e58c0d

**Comment by amunra** [comment]
It looks like the fix introduced by https://github.com/zakarumych/allocator-api2/commit/a16a359038cf741aa6445809e33a845e17e58c0d no longer appears in `stable/mod.rs`.

In other words, the bug is still there and the `Vec::try_reserve` API can't be compiled without nightly.
